# Generated by Django 5.1.4 on 2025-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_experiences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='total_years_of_experience',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
