# Generated by Django 5.1.4 on 2025-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_resume_job_experiences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='extracted_text',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_experiences',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='total_years_of_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='current_designation',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='experiences',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='Not Mentioned', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(default='Not Mentioned'),
            preserve_default=False,
        ),
    ]
